repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v4.3.21'
      hooks:
      - id: isort
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v2.3.0'
      hooks:
        - id: check-merge-conflict
        - id: flake8
