version: '3'

services:
  app:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    image: crawler_helper:latest
    container_name: crawler
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
