version: '3.4'

services:
  message_broker:
    image: rabbitmq:3.7-alpine
    container_name: rabbitmq_crawler
    expose:
      - 5672
  database:
    image: postgres:11-alpine
    container_name: postgres_crawler
    expose:
      - 5432
  migrate:
    image: &img "umat/crawler_helper:${SEMAPHORE_WORKFLOW_ID}"
    restart: on-failure:50
    env_file: &env_file
      - ~/secrets.env
    command: ash -c "python manage.py migrate"
    depends_on:
      - database

  worker:
    image: *img
    command: [celery, -A, crawler, worker, -l, info]
    depends_on:
      - message_broker
    env_file: *env_file
    restart: on-failure

  app:
    working_dir: /app
    image: *img
    container_name: crawler
    depends_on:
      - message_broker
      - database
      - migrate
    env_file: *env_file
    expose:
      - 8000
    volumes:
      - .:/app
    restart: on-failure
    command: ash -c "python manage.py runserver 0.0.0.0:8000"
