version: '3.4'

services:
  message_broker:
    image: rabbitmq:3.7-alpine
    container_name: rabbitmq_crawler
    ports:
      - '5672:5672'
  database:
    image: postgres:11-alpine
    container_name: postgres_crawler
    volumes:
      - ./postgres_crawler:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: crawler_helper:latest
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres@postgres_crawler:5432/postgres
    volumes:
      - ./:/app/
    command: ash -c "python manage.py migrate"
    depends_on:
      - database
#  app:
#    working_dir: /app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: crawler_helper:latest
#    container_name: crawler
#    depends_on:
#      - message_broker
#      - database
#      - migrate
#    ports:
#      - '8000:8000'
#    volumes:
#      - .:/app
#    command: ash -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
