# Generated by Django 2.2.5 on 2019-09-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, null=True)),
                ('line_number', models.CharField(max_length=10, null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BusStop')),
            ],
        ),
        migrations.AddField(
            model_name='busstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.City'),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('city', 'name')},
        ),
    ]
