# Generated by Django 2.2.5 on 2019-09-20 07:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


def copy_timetables_to_timetable_link(apps, schema_editor):
    Timetable = apps.get_model('collector', 'Timetable')
    TimetableLink = apps.get_model('collector', 'TimetableLink')

    for timetable in Timetable.objects.all():
        tl = TimetableLink(
            link=timetable.link,
            line_number=timetable.line_number,
            last_update=timetable.last_update,
            bus_stop=timetable.bus_stop,
        )
        tl.save()


def copy_timetable_links_to_timetable(apps, schema_editor):
    Timetable = apps.get_model('collector', 'Timetable')
    TimetableLink = apps.get_model('collector', 'TimetableLink')

    for timetable_link in TimetableLink.objects.all():
        tt = Timetable(
            link=timetable_link.link,
            line_number=timetable_link.line_number,
            last_update=timetable_link.last_update,
            bus_stop=timetable_link.bus_stop,
        )
        tt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
                ('line_number', models.CharField(max_length=10, null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BusStop')),
            ],
        ),
        migrations.RunPython(copy_timetables_to_timetable_link, copy_timetable_links_to_timetable),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
