# Generated by Django 2.2.5 on 2019-09-23 14:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20190920_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='collector.City'),
        ),
    ]
